# Set asan
#LD_PRELOAD_CMD=`gcc -print-file-name=libasan.so`
#LD_PRELOAD_CMD=`clang -print-file-name=libclang_rt.asan-x86_64.so`

all:
	#LD_PRELOAD=$(LD_PRELOAD_CMD) python simple_tokenize.py
	python simple_tokenize.py

